
version : "3.8"

services:
  redis:
    image: redis
    ports:
      - 6379

  backend-ex:
      build: 
        context: ./
        dockerfile: Dockerfile_b
      environment: 
        - REDIS=redis
        - FRONT_URL=http://localhost:5000
      ports: 
        - 8000:8000
  frontend-ex:
      build:
        context: ./
        dockerfile: Dockerfile_f
      environment: 
        - API_URL=http://localhost:8000
      ports:
        - 5000:5000
