
version : "3.8"

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=postgres

  redis:
    image: redis
    ports:
      - 6379

  backend-ex:
      build: 
        context: ./
        dockerfile: Dockerfile_b
      environment: 
        - REDIS=redis
        - DB_HOST=db
        - DB_USERNAME=user
        - DB_PASSWORD=a
        - DB_NAME=postgres
      depends_on:
      - redis
      - db
      volumes:
        - ./logs.txt:/usr/app/logs.txt
  frontend-ex:
      build:
        context: ./
        dockerfile: Dockerfile_f
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend-ex
