FROM node:13 

WORKDIR /mydir/front
COPY ./Frontend .
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install
EXPOSE 5000
CMD API_URL=http://localhost:8000 npm start
