FROM node:13 

WORKDIR /mydir/back
COPY ./Backend .
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install
EXPOSE 8000
CMD FRONT_URL=http://localhost:5000 npm start
